server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/asa
    username: asa
    password: asa
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${ASA_MAIL_USERNAME:asadiretoresmmo@gmail.com}
    password: ${ASA_MAIL_PASSWORD:ALTERE_A_SENHA}
    protocol: smtp
    test-connection: ${ASA_MAIL_TEST_CONNECTION:false}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: false
            trust: smtp.gmail.com
          connectiontimeout: 300000
          timeout: 300000
          writetimeout: 300000
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
app:
  jwt:
    secret: change-this-secret-please-change-this-secret
    expiration-minutes: 480
  email:
    nome-exibicao: "Asa - Acao Solidaria Adventista"
    pop:
      host: pop.gmail.com
      port: 995
      ssl: true
